# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include: ['master']

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet restore ./All.sln
  displayName: Restore
#workingDirectory: $(workingDirectory)

- script: dotnet build ./All.sln --configuration $(buildConfiguration)
  displayName: Build
#  workingDirectory: $(workingDirectory)

